import { sample, capitalizeAll } from '../utils';

export const generateRandomName = () => {
  const source = sample(['assembled-phrase', 'intel-codenames']);

  let name;
  if (source === 'assembled-phrase' || true) {
    name = capitalizeAll(`${sample(adjectives)} ${sample(nouns)}`);
  } else {
    name = sample(intelCodenames);
  }

  return name;
};

const adjectives = [
  'clean',
  'elegant',
  'magnificent',
  'charming',
  'whimsical',
  'glamorous',
  'stylish',
  'mango', // I know, but it works if you think of it as the color
  'ambitious',
  'brave',
  'wonderful',
  'witty',
  'sassy',
  'thunder',
  'lightning',
  'stormy',
  'sunny',
  'rhythmic',
  'old-fashioned',
  'fresh',
  'vivacious',
  'calming',
  'delightful',
  'nutritious',
  'icy',
  'abundant',
  'incalculable',
  'substantial',
  'jovial',
  'snow',
  'magic',
  'magical',
];

const animalNames = [
  'cat',
  'dog',
  'ocelot',
  'lynx',
  'ferret',
  'capybara',
  'narwhal',
  'fox',
  'raccoon',
  'camel',
  'goat',
  'jaguar',
  'tiger',
  'lion',
  'panther',
  'leopard',
  'bobcat',
];

const objects = [
  'toaster',
  'microwave',
  'blender',
  'kettle',
  'fireworks',
  'thing',
  'plane',
  'spork',
  'storybook',
  'planet',
  'bottle',
  'tea',
  'coffee',
];

const nouns = [...animalNames, ...objects];

const intelCodenames = [
  'Acacia',
  'Agate',
  'Airmont',
  'Aitkens',
  'Aladdin',
  'Alberta',
  'Alcolu',
  'Alder Poca',
  'Alderwood',
  'Alfredo',
  'Aliceton',
  'Alief',
  'Allendale',
  'Almador',
  'Alpine Ridge',
  'Alta',
  'Altair',
  'Alton Bay',
  'Alviso',
  'Anchorage',
  'Anchor Creek',
  'Andrews Lake',
  'Aneroid Lake',
  'Anvik',
  'Apalachia',
  'Apollo',
  'Apple Glenn',
  'Argus SR',
  'Aries',
  'Arrandale',
  'Aruba',
  'Ashland',
  'Aspen Cabrillo',
  'Aspen Drake',
  'Aspen Hill',
  'Atlanta',
  'Atlantis',
  'Attla',
  'Atwood',
  'Auburndale',
  'Aubrey Isle',
  'Augsburg',
  'Aurora',
  'Avalon',
  'Averill',
  'Avoton',
  'Azalia',
  'Bad Axe',
  'Bad Axe 2',
  'Baker Bay',
  'Balboa',
  'Bali',
  'Bali',
  'Baldry Mt.',
  'Bandera',
  'Bangor',
  'Banias',
  'Banister',
  'Bar Harbor',
  'Barnroof Point',
  'Bartman',
  'Barton Hills',
  'Bartonville',
  'Batman',
  "Batman's Revenge",
  'Baton Rouge',
  'Battle Lake',
  'Baxter Peak',
  'Bayfield',
  'Baytown',
  'Bay Trail',
  'Bear Canyon',
  'Bearlake',
  'Bear Point',
  'Bear Ridge',
  'Beartooth Pass',
  'Bearup Lake',
  'Beckton',
  'Bellefontaine',
  'Bensley',
  'Berg Lake',
  'Berryville',
  'Bigby',
  'Bighorn Peak',
  'Big Lake',
  'Big Laurel',
  'Big Sur',
  'Billings',
  'Bimini',
  'Birchwood',
  'Bisbee',
  'Blackford',
  'Black Canyon',
  'Black Canyon-2',
  'Black Creek',
  'Black Pine',
  'Black Rapids',
  'Bloomfield',
  'Blue Hills',
  'Blue Mountain',
  'Bluff Creek',
  'Boazman',
  'Bobcat Peak',
  'Boiler Bay',
  'Bolton',
  'Bonanza',
  'Bonetrail',
  'Bonham',
  'Bonita',
  'Bonnell',
  'Bordenville',
  'Boston',
  'Boulder Creek',
  'Boxboro',
  'Bozeman',
  'Braiden Creek',
  'Braidwood',
  'Brakefield Bend',
  'Brandon',
  'Breeds Hill',
  'Bretona',
  'Brickland',
  'Bridge Creek',
  'Briertown',
  'Broadwater',
  'Broadwell',
  'Bromolow',
  'Brookdale',
  'Brownsville',
  'Brownsville-2',
  'Bryson',
  'Buckeye',
  'Buckner',
  'Buffalo Creek',
  'Buffalo Flat',
  'Bull Mountain',
  'Bulverde',
  'Burrage',
  'Byfield',
  'Byfield Lite',
  'Byrd',
  'Byrd II',
  'Cabot',
  'Cactus Ridge',
  'Caldwell',
  'Calexico',
  'Calexico 2',
  'Calistoga',
  'Callahan',
  'Calpella',
  'Camino',
  'Caneland',
  'Canmore',
  'Cannon Lake',
  'Cannonville',
  'Canoe Creek',
  'Canoe Lake',
  'Canoe Pass',
  'Canterwood',
  'Canterwood-ES',
  'Cantiga',
  'Canyon Peak',
  'Cape Cod',
  'Capulet',
  'Carbonado',
  'Cariboo River',
  'Carlow',
  'Carmack',
  'Carmel',
  'Carretta',
  'Cascades',
  'Castine',
  'Castle Point',
  'Caswell',
  'Cave Creek',
  'Cayman',
  'Cayman 2',
  'Cedarview',
  'Cedar Cove',
  'Cedar Mill',
  'Cedar Trail',
  'Centerton',
  'Chattanooga',
  'Cherry Creek',
  'Cherryville',
  'Chevelon',
  'Chief River',
  'Chilito',
  'Chilito 2',
  'Chisholm Trail',
  'Chivano',
  'Cibolo',
  'Clackamas',
  'Claremont',
  'Clarkdale',
  'Clarksboro',
  'Clarksfield',
  'Clarkville',
  'Clear Bay',
  'Clear Fork',
  'Clearwater',
  'Clems Cove',
  'Clovertown',
  'Cloverview',
  'Clover Trail',
  'Coconut Creek',
  'Coffee Lake',
  'Cold Lake',
  'Colleyville',
  'Colusa',
  'Comanche Creek',
  'Condor Peak',
  'Conroe',
  'Cooper River',
  'Coos Bay',
  'Coppermine',
  'Copper Pass',
  'Copper Pond',
  'Copper River',
  'Cordova',
  'Corner Field',
  'Corsair',
  'Cortez',
  'Coryville',
  'Cotulla',
  'Cougar Canyon',
  'Cougar Point',
  'Coupeville',
  'Covington',
  'Coyanosa',
  'Cranberry Lake',
  'Cranford',
  'Creede',
  'Crestline',
  'Crow Point',
  'Crown Bay',
  'Crown Beach',
  'Crown Pass',
  'Crystal Forest',
  'Cube Cove',
  'Culver City',
  'Culver City 2',
  'Cumberland',
  'Cypress',
  'Dakota',
  'Dalhart',
  'Dana Point',
  'Danbury',
  'Dandale',
  'Dayville',
  'Decathlete',
  'Deerfield',
  'Deer Flat',
  'Dempsey',
  'Denali',
  'Dermot',
  'Deschutes',
  "Devil's Canyon",
  'Dewey Beach',
  'Diamond Lake',
  'Diamondville',
  'Dimona',
  'Dixon',
  'Dodson',
  'Dothan',
  'Double Barrow',
  'Doug Lake',
  'Dover',
  'Dowling-T',
  'Downey',
  'Dragontail Peak',
  'Drake',
  'Driskill-T',
  'Dry Fork',
  'Dublin',
  'Dunes Beach',
  'Dunellen',
  'Dunnington',
  'Eaglelake',
  'Eagle Ridge',
  'East Fork',
  'Eastern Point',
  'Easton',
  'Eatonville',
  'Eb Lake',
  'Echo Peak',
  'Eden Prairie',
  'Eklo',
  'Ekron',
  'Eldridge',
  'Elmcrest',
  'Emerald Bay',
  'Emerald Lake',
  'Emerald Lake 2',
  'Endeavor',
  'Englewood',
  'Entrada',
  'Ephraim',
  'Eva Cove',
  'Evans Peak',
  'Everson',
  'Fairbanks',
  'Fair Oaks',
  'Fanwood',
  'Fayetteville',
  'Fiji',
  'Flaxton',
  'Fly Creek',
  'Forest Lake',
  'Fort Sumter',
  'Fortville',
  'Foster',
  'Foxhollow',
  'Foxton',
  'Fox Cove',
  'Free Town',
  'Frostburg',
  'Gainestown',
  'Gainesville',
  'Gallatin',
  'Gallaway',
  'Gamla',
  'Gardendale',
  'Garden Island',
  'Garlow',
  'Gasper',
  'Gaston',
  'Geneseo',
  'Gesher',
  'Gilgal',
  'Gilo',
  'Glen Brook',
  'Glen Ridge',
  'Glenwood',
  'Glidewell',
  'Glyndon',
  'Golan',
  'Grand County',
  'Granite Bay',
  'Grantley-EP',
  'Grantsdale',
  'Green Fountain',
  'Greencreek',
  'Grizzly Pass',
  'Grosse Point',
  'Groveland',
  'Guardfish',
  'Gulftown',
  'Hammonton',
  'Hanksville',
  'Hanlan Creek',
  'Harpertown',
  'Hartwell',
  'Haswell',
  'Havendale',
  'Havre',
  'Hawley Creek',
  'Hayden Valley',
  'Hazleton',
  'Hendrixx',
  'Hillel',
  'Hondo',
  'Houlton Legacy',
  'Huron River',
  'Ibex Peak',
  'Ice Lake',
  'Iron Falls',
  'Ironlake',
  'Iron Pass',
  'Iron Pond',
  'Irwindale',
  'Ivy Bridge',
  'Jaketown',
  'Jackson',
  'Ivytown',
  'Jasper Forest',
  'Jayhawk',
  'Jefferson Pass',
  'Johannesburg',
  'Johnstown',
  'Jones Beach',
  'Jordan Creek',
  'Juneau',
  'Kaby Lake',
  'Katmai',
  'Kauai',
  'Kawela',
  'Kaylo',
  'Kedron',
  'Keifer',
  'Kenai',
  'Kenosha Pass',
  'Kentsfield',
  'Kevet',
  'Kikayon',
  'King Crest',
  'Kings Creek',
  'Kingsport 3',
  'Kinnereth',
  'Kinston',
  'Kirkwood',
  'Kittson',
  'Klamath',
  'Knights Corner',
  'Knights Ferry',
  'Knights Landing',
  'Knoll Creek',
  'Kyrene',
  'L52A',
  'L62A',
  'L63A',
  'L63B',
  'L73A',
  'L74A',
  'L84A',
  'La Crosse',
  'LaGrande',
  'La Mesa',
  'Lakeport',
  'Langwell',
  'Larrabee',
  'Larson Creek',
  'Lavon',
  'Layton',
  'Lewisville',
  'Lewisburg',
  'Light Peak',
  'Light Ridge',
  'Lincoln Crest',
  'Lincroft',
  'Lindenhurst',
  'Little Falls',
  'Little Falls 2',
  'Little River',
  'Liven Good',
  'Lizard Head Pass',
  'Long Cove',
  'Lunaville',
  'Luxemburg',
  'Lyndonville',
  'Lynnfield',
  'MacKenzie',
  'Madison',
  'Maho Bay',
  'Maple Crest',
  'Marathon',
  'Marblehead',
  'Marlinspike',
  'Mars',
  'Marshalltown',
  'Matanzas',
  'Maywood',
  'McCaslin',
  'McCreary',
  'McKinley',
  'Medfield',
  'Mendocino',
  'Menlow',
  'Merced',
  'Mercury',
  'Merom',
  'Merrifield',
  'Millbrook',
  'Millington',
  'Millville',
  'Moab',
  'Mobile Bay',
  'Monahans',
  'Montara',
  'Montecito',
  'Montevina',
  'Montpelier',
  'Montvale',
  'Moorestown',
  'Morgan Hill',
  'Morrison',
  'Mount Prospect',
  'Mount Union DVI',
  'Mount Washington',
  'Mukilteo',
  'Napa',
  'Natoma',
  'Navy Pier',
  'Nehalem',
  'Neptune',
  'Newberry Lake',
  'Niantic',
  'Nine Mile',
  'Ninja',
  'Nineveh',
  'Nocona',
  'Northwood',
  'Novarupta',
  'Oak Trail',
  'Odem',
  'Ophir',
  'Oplin',
  'Orchid Island',
  'Orion',
  'Paint Creek',
  'Palm Canyon',
  'Panther Point',
  'Patsburg',
  'Paxville',
  'Pellston',
  'Pendleton',
  'Penryn',
  'Penwell',
  'Petrof Bay-T',
  'Picket Post',
  'Piketon',
  'Pilot Point',
  'Pilot Point-T',
  'Pine Trail',
  'Pineview',
  'Placer',
  'Plato',
  'Pleiades',
  'Plumas',
  'Plum Creek',
  'Plum Island',
  'Polar',
  'Polaris',
  'Pondicherry',
  'Portland',
  'Portville',
  'Postville',
  'Postville Refresh',
  'Potomac',
  'Poulsbo',
  'Poulson',
  'Powerville',
  'Prague',
  'Prescott',
  'Presler',
  'Prestonia',
  'Providence',
  'Puget Island',
  'Purley',
  'Queens Bay',
  'Radio Springs',
  'Ralston Peak',
  'Ramsdale',
  'Rapid City',
  'Red Ridge',
  'Redwater',
  'Red Rock Canyon',
  'Reidland',
  'Rexburg',
  'Richford',
  'Riggins-T',
  'Rimon',
  'Rio Vista',
  'River Trail',
  'Robson',
  'Rochester',
  'Rock Creek',
  'Rock Harbor',
  'Rock Lake',
  'Rockwell',
  'Romley',
  'Rosepoint',
  'Rose Hill',
  'Salt Creek',
  'Saltwell',
  'San Clemente',
  'Sandusky',
  'Sandy Bridge',
  'Sandy Canal',
  'Santa Rosa',
  'Saturn',
  'Saturn II',
  'Scanlon Bay',
  'Sea Breeze',
  'Seaburg',
  'Seacliff Trail',
  'Seattle',
  'Shady Cove',
  'Sharkey',
  'Shark Bay',
  'Sheepshead Bay',
  'Shell Bay',
  'Shelter Island',
  'Shelton',
  'Shiloh',
  'Shirley Peak',
  'Shoal Creek',
  'Sibley',
  'Sierra Grande',
  'Siler',
  'Silvermont',
  'Silver Reef',
  'Silverthorne',
  'Silvervale',
  'Skulltrail',
  'Skylake',
  'Smackover 2',
  'Smithfield',
  'Snow Hill',
  'Soda Creek',
  'Sodaville',
  'SoFIA',
  'Solano',
  'Sonoma',
  'Sorrento',
  'Sossaman',
  'South Bend',
  'South Lake',
  'Spring Fountain',
  'Spring Meadow',
  'Springdale',
  'Stealey',
  'Stebbins 2',
  'Stellarton',
  'Stoakley',
  'Stoneville',
  'Stonylake',
  'Stormville [59]',
  'Stoutland',
  'Strawberry Mountain',
  'Sugar Bay',
  'Sunnymead',
  'Sunrise Lake',
  'Tabor',
  'Tabor II',
  'Tabor 3',
  'Tahiti',
  'Tanacross',
  'Tanglewood',
  'Tanner',
  'Tappen',
  'Taylorsville',
  'Tehama',
  'Tejas',
  'Tekoa',
  'Thete',
  'Thor',
  'Thorsby',
  'Thurley',
  'Tiger Point',
  'Tigerton',
  'Tillamook',
  'Timber Creek',
  'Timna',
  'Tolapai',
  'Tonga',
  'Topcliff',
  'Triton',
  'Truland',
  'Trumbull',
  'Tualatin',
  'Tukwila',
  'Tulloch',
  'Tulsa',
  'Tunnel Creek',
  'Tunnel Mountain',
  'Tumwater',
  'Tupelo',
  'Twin Castle',
  'Twinville',
  'Tylersburg',
  'Tyax',
  'Union Peak',
  'Urbanna',
  'Val Vista',
  'Valley Island',
  'Valleyview',
  'Vancouver',
  'Vanderpool',
  'Vanguard',
  'Venus',
  'Victor Island',
  'Vidalia',
  'Villanova',
  'Waimea Bay',
  'Walnut Grove',
  'Warm River',
  'Warm Springs',
  'Washington Pass',
  'Wellsburg',
  'West Branch',
  'Westmere',
  'Weybridge',
  'Whale Cove',
  'Whitefield',
  'Whitesburg',
  'White Salmon',
  'Whitmore Lake',
  'Whitney',
  'Whitney Point',
  'Wichita',
  'Wildwood Trail',
  'Wilkins Peak',
  'Willamette',
  'Willapa Bay',
  'Willowbrook',
  'Willow Springs',
  'Willow Springs 2',
  'Windigo',
  'Windmill',
  'Winnipeg',
  'Winterset',
  'Winter Park',
  'Wolfdale',
  'Woodcrest',
  'Woodinville',
  'Woodridge',
  'Woodruff',
  'Woodsworth',
  'Wyloway',
  'Yamhill',
  'Yampai',
  'Yonah',
  'Yorkfield',
  'Zanesville',
  'Zappa',
  'Zellwood',
  'Zion',
  'Zoar',
];
